### ISSUE TITLE
Notification for Gitlab events (open MR, comment, etc) ?

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#40]

**Comment by nclsHart** [comment]
Yep great idea. 

IMO, we must allow user to disable/configure it.

**Comment by ghost** [comment]
:+1:

**Comment by nclsHart** [comment]
I think we need to go further than just notify on GitLab events. In order to give meaning and some interest to this feature, we should create our own notifications based on GitLab events.

Examples : 
- The MR "lorem ipsum" is ready to be merged => MR with at least one approval and CI success
- John Doe approves MR "lorem ipsum"
- MR "lorem ipsum" is now ready for review => CI was in failure and goes into success
- ...
